### ISSUE TITLE
How to change the font and font-size?

### ISSUE THREAD

**Issue by NewSkyLine-dev** [stack/walnut-apple#1]
I would like to change the Font as well the font size, where am I doing this? I can see a
```cpp
io.Fonts->AddFontFromFileTTF(...);
``` 
in **Application.cpp**, but when I change it, nothing changes.
So how do I change it?
Help would be appreciated. 😃

**Comment by stack** [comment]
If you look at the code above it, I am resolving the path to the font in the application bundle. Each font is bundled with the application, as ImGui is loading its data directly from files, not from the operating system.

The fonts are stored in the Xcode project under `Walnut/Fonts`. These are also included in the Build Phases of the apps to copy them in to place.

If you wanted your own font, you would need to do something similar.

**Comment by NewSkyLine-dev** [comment]
Thanks, made it work with copying my otf file via my CMakeLists 👍🏻
